#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'table_print' # TODO: Should be required in another file
require_relative 'lib/yabs'

application = Yabs::Application.new('yabs')
exit application.run(ARGV)
